### PR TITLE
bumped version to 2.0.1

### PR DESCRIPTION
**Pull request by kagux**

### CODE REVIEW

**Comment by kagux** [comment]
@benwilson512 merging works now! However, I can't merge in trivial changes like this one without a review. Is this how you'd like to keep it? On the same note, what's your policy/workflow with hex publishing?

**Comment by benwilson512** [comment]
@kagux At first I think it's important to have the review flow. Are you able to review it yourself?

On this actual PR though since it isn't actually released on hex yet as v2.0. I do plan on giving you hex publish access, I just want to do the initial setup. I'm hoping I can get this out today, just gotta finish some docs on ExAws itself.

**Comment by kagux** [comment]
No, I can't review myself. 
Got it regarding hex, sounds good!

**Comment by benwilson512** [comment]
Ah, still getting used to the github controls sorry. Ok, you should no longer need a review, and I'm pretty sure you can just push to master. On the whole though it'd be good if we stuck to PRs.

Gonna close this one out cause there's no point in doing a 2.0.1 until there's an actual 2.0 release.

**Pull request closed without merging**
